# Generated by Django 4.2.5 on 2023-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('patient', 'Patient'), ('PA', 'Personal Assistant'), ('hospital', 'Hospital'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
    ]
