# Generated by Django 4.2.5 on 2023-09-23 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0007_doctor_card_id'),
        ('Appointment', '0002_appointment_estimated_time_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
