# Generated by Django 4.2.5 on 2023-09-21 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chronic_illness', models.TextField(blank=True, help_text='diabetes, hypertension, etc.', max_length=1000, null=True)),
                ('acute_illness', models.TextField(blank=True, help_text='fever, cold, etc.', max_length=1000, null=True)),
                ('allergies', models.TextField(blank=True, help_text='drug allergies, food allergies, dust allergies, etc.', max_length=1000, null=True)),
                ('family_history', models.TextField(blank=True, help_text='Family history of medical conditions', max_length=1000, null=True)),
                ('current_medication', models.TextField(blank=True, help_text='Current medications (including dosage and frequency)', max_length=1000, null=True)),
                ('past_medication', models.TextField(blank=True, help_text='Previous medications and treatment regimens', max_length=1000, null=True)),
                ('prescription', models.TextField(blank=True, help_text='Prescription History', max_length=1000, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Patient.patient')),
            ],
        ),
    ]
