# Generated by Django 4.2.5 on 2023-09-20 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_operatingdays_doctor_user_alter_doctor_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OperatingDays',
            new_name='OperatingDay',
        ),
        migrations.RenameModel(
            old_name='OperatingHours',
            new_name='OperatingHour',
        ),
    ]
