# Generated by Django 4.2.5 on 2023-09-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0005_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
